version: "2.2"

# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# https://www.elastic.co/guide/en/kibana/current/docker.html

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge

services:
  es-learn1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es-learn
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es-learn
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - esnet

  kibana-learn:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana-learn
    environment:
      ELASTICSEARCH_HOSTS: http://es-learn:9200
    depends_on:
      - es-learn
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5602:5601
    networks:
      - esnet
